### ISSUE TITLE
About your pre-trained model

### ISSUE THREAD

**Issue by zyq950309** [yiling-chen/view-finding-network#4]
The pre-trained model you provides has many tensors, such as Variable_5/Adam_1,  Variable_1,
ranker/fc6w,  ranker/fc6b,  ranker/fc6b/Adam,  ranker/fc6w/Adam and so on. I wonder which one should I choose for fc6W and fc6b in network.py? or what is the correspondence between these tensor values and the weights in network.py?How should I use it? Thank you very much!

**Comment by zyq950309** [comment]
And I use    
    fc6W = graph.get_tensor_by_name('ranker/fc6w:0')
    fc6b = graph.get_tensor_by_name('ranker/fc6b:0')
but each run gives me a different score.......

**Comment by kloppjp** [comment]
The associations are correct, ranker/fc6w is fc6W and ranker/fc6b is fc6b, the other variables (.../Adam) are created by the optimizer and are not used if you run only inference. From the code you've posted in your comment, it's not clear where the problem is as you are merely fetching the references to the tensors in the computational graph. Please refer to our code on how to correctly load the model parameters and run the inference.

**Comment by zyq950309** [comment]
Thank you very much. My problem is solved.
